---
roles:
  - name: agoloncser.git
    version: master
  - name: agoloncser.git_config
    version: master
  - name: agoloncser.git_repos
    version: master
  - name: agoloncser.emacs
    version: master
  - name: agoloncser.pyenv
    version: master
