---
name: Galaxy install test
on:
  push: {}
  pull_request: {}
  schedule:
    - cron: "12 * * * *"

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - name: Install dependencies
        run: pip install ansible

      - name: Installing from galaxy
        working-directory: "${{ github.repository }}"
        run: |
          type ansible
          ansible --version
          type ansible-galaxy
          ansible-galaxy --version
          ansible-galaxy install -fr requirements.yml
          ansible-galaxy role list
