---
name: Molecule testing
on:
  push: {}
  pull_request: {}
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "*/15 * * * *"

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: pip install ansible

      - name: Molecule test
        run: ansible-galaxy install -fr requirements.yml
